CREATE DATABASE momoshiroi_portfolio;

USE momoshiroi_portfolio;

CREATE TABLE EVENTS (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  image VARCHAR(255) NOT NULL,
  caption TEXT NOT NULL
);

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL
);


SELECT * FROM users

DROP TABLE users;


CREATE TABLE eventmomoshiroi(
  id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
  title VARCHAR(255) NOT NULL,
  caption TEXT NOT NULL,
  image VARCHAR(255) NOT NULL,
  created_at DATE DEFAULT (CURRENT_DATE)
)ENGINE=INNODB;